# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Project properties
group=dev.lambdaurora
java_version=21

# Mod Properties
mod_version=2.0.1
archives_base_name=lambdabettergrass
modrinth_id=2Uev7LdA
curseforge_id=400322

fabric.loom.dropNonIntermediateRootMethods=true
