# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.configuration-cache=true

# Project properties
group=dev.lambdaurora
java_version=25

# Mod Properties
mod_version=2.8.1
mod_namespace=lambdabettergrass
mod_description=Adds actual better grass and better snow while being customizable!
fabric_mc_constraints=~26.2-
modrinth_id=2Uev7LdA
curseforge_id=400322

fabric.loom.dropNonIntermediateRootMethods=true
