# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.configuration-cache=true

# Project properties
group=dev.lambdaurora.lambdabettergrass
java_version=21

# Mod Properties
base_version=2.0.4
archives_base_name=lambdabettergrass
compatible_mc_versions=1.21
fabric_mc_constraints=~1.21 <1.21.2-
neoforge_mc_constraints=[1.21,1.21.1]
neoforge_version=21.1.233
modrinth_id=2Uev7LdA
curseforge_id=400322

fabric.loom.dropNonIntermediateRootMethods=true
