[versions]
minecraft = "1.21.3"
fabric-loader = "0.16.14"
fabric-api = "0.114.1+1.21.3"
mappings-yalmm = "6"

# Dependencies
yumi-mc-foundation = "1.0.0-alpha.7+1.21.1"
spruceui = "6.2.2+1.21.4"
modmenu = "12.0.0"

# Configuration
nightconfig = "3.8.1"

# Gradle
gradle-licenser = "2.1.+"
gradle-loom = "1.11.+"
gradle-lambdamcdev = "1.4.+"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }

# Dependencies
yumi-mc-foundation = { module = "dev.yumi.mc.core:yumi-mc-foundation", version.ref = "yumi-mc-foundation" }
spruceui = { module = "dev.lambdaurora:spruceui", version.ref = "spruceui" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }

# Configuration
nightconfig-core = { module = "com.electronwill.night-config:core", version.ref = "nightconfig" }
nightconfig-toml = { module = "com.electronwill.night-config:toml", version.ref = "nightconfig" }

[plugins]
licenser = { id = "dev.yumi.gradle.licenser", version.ref = "gradle-licenser" }
loom = { id = "fabric-loom", version.ref = "gradle-loom" }
lambdamcdev = { id = "dev.lambdaurora.mcdev", version.ref = "gradle-lambdamcdev" }
