[versions]
minecraft = "1.21.9"
fabric-loader = "0.17.2"
fabric-api = "0.133.14+1.21.9"
mappings-yalmm = "8"

# Dependencies
yumi-mc-foundation = "1.0.0-alpha.16+1.21.9"
spruceui = "9.0.0+1.21.9"
modmenu = "15.0.0-beta.3"

# Configuration
nightconfig = "3.8.1"

# Gradle
gradle-licenser = "2.1.+"
gradle-loom = "1.11.+"
gradle-lambdamcdev = "1.6.+"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }

# Dependencies
yumi-mc-foundation = { module = "dev.yumi.mc.core:yumi-mc-foundation", version.ref = "yumi-mc-foundation" }
spruceui = { module = "dev.lambdaurora:spruceui", version.ref = "spruceui" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }

# Configuration
nightconfig-core = { module = "com.electronwill.night-config:core", version.ref = "nightconfig" }
nightconfig-toml = { module = "com.electronwill.night-config:toml", version.ref = "nightconfig" }

[plugins]
licenser = { id = "dev.yumi.gradle.licenser", version.ref = "gradle-licenser" }
loom = { id = "fabric-loom", version.ref = "gradle-loom" }
lambdamcdev = { id = "dev.lambdaurora.mcdev", version.ref = "gradle-lambdamcdev" }
