[versions]
minecraft = "26.1.2"
fabric-loader = "0.18.5"
fabric-api = "0.152.1+26.1.2"

# Dependencies
yumi-mc-foundation = "1.1.0+26.1"
spruceui = "10.0.0+26.1"
modmenu = "18.0.0-beta.1"
sodium = "0.8.7+mc26.1"

# Configuration
nightconfig = "3.8.1"

# Gradle
gradle-licenser = "4.0.+"
gradle-loom = "1.16.+"
gradle-lambdamcdev = "2.2.+"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }

# Dependencies
yumi-mc-foundation = { module = "dev.yumi.mc.core:yumi-mc-foundation", version.ref = "yumi-mc-foundation" }
spruceui = { module = "dev.lambdaurora:spruceui", version.ref = "spruceui" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
sodium-api = { module = "net.caffeinemc:sodium-fabric-api", version.ref = "sodium" }

# Configuration
nightconfig-core = { module = "com.electronwill.night-config:core", version.ref = "nightconfig" }
nightconfig-toml = { module = "com.electronwill.night-config:toml", version.ref = "nightconfig" }

[plugins]
licenser = { id = "dev.yumi.gradle.licenser", version.ref = "gradle-licenser" }
loom = { id = "net.fabricmc.fabric-loom", version.ref = "gradle-loom" }
lambdamcdev = { id = "dev.lambdaurora.mcdev", version.ref = "gradle-lambdamcdev" }
