name: "Gradle Build"

on:
  push:
    branches:
      - "*"
  pull_request:
concurrency: build-${{ github.sha }}

jobs:
  build:
    strategy:
      matrix:
        java: [ 17, 21, 24 ]
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Set up Java"
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}
      - name: "Set up Gradle"
        uses: gradle/actions/setup-gradle@v3
      - name: "Gradle Build"
        run: ./gradlew build --stacktrace --parallel
      - name: "Upload artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts_j${{ matrix.java }}
          path: ./build/libs/
